import { db } from "@workspace/db";
import { songs } from "@workspace/db";

const SEED_SONGS = [
  // Classic Rock
  { title: "Livin' on a Prayer", artist: "Bon Jovi", bpm: 123, genre: "Rock", durationMinutes: 4.1, energyScore: 9 },
  { title: "You Give Love a Bad Name", artist: "Bon Jovi", bpm: 123, genre: "Rock", durationMinutes: 3.9, energyScore: 9 },
  { title: "Wanted Dead or Alive", artist: "Bon Jovi", bpm: 76, genre: "Rock", durationMinutes: 5.1, energyScore: 6 },
  { title: "It's My Life", artist: "Bon Jovi", bpm: 120, genre: "Rock", durationMinutes: 3.7, energyScore: 8 },
  { title: "Bad Medicine", artist: "Bon Jovi", bpm: 130, genre: "Rock", durationMinutes: 5.2, energyScore: 9 },
  { title: "Don't Stop Believin'", artist: "Journey", bpm: 118, genre: "Rock", durationMinutes: 4.1, energyScore: 9 },
  { title: "Any Way You Want It", artist: "Journey", bpm: 133, genre: "Rock", durationMinutes: 3.2, energyScore: 9 },
  { title: "Open Arms", artist: "Journey", bpm: 70, genre: "Rock", durationMinutes: 3.3, energyScore: 5 },
  { title: "Faithfully", artist: "Journey", bpm: 76, genre: "Rock", durationMinutes: 4.4, energyScore: 5 },
  { title: "Bohemian Rhapsody", artist: "Queen", bpm: 72, genre: "Rock", durationMinutes: 5.9, energyScore: 7 },
  { title: "Don't Stop Me Now", artist: "Queen", bpm: 156, genre: "Rock", durationMinutes: 3.6, energyScore: 10 },
  { title: "We Are the Champions", artist: "Queen", bpm: 63, genre: "Rock", durationMinutes: 3.0, energyScore: 7 },
  { title: "Under Pressure", artist: "Queen & David Bowie", bpm: 109, genre: "Rock", durationMinutes: 4.1, energyScore: 8 },
  { title: "Somebody to Love", artist: "Queen", bpm: 76, genre: "Rock", durationMinutes: 4.6, energyScore: 7 },
  { title: "Radio Ga Ga", artist: "Queen", bpm: 113, genre: "Rock", durationMinutes: 5.5, energyScore: 7 },
  { title: "We Will Rock You", artist: "Queen", bpm: 81, genre: "Rock", durationMinutes: 2.0, energyScore: 8 },
  { title: "Another One Bites the Dust", artist: "Queen", bpm: 110, genre: "Rock", durationMinutes: 3.6, energyScore: 8 },
  { title: "Mr. Brightside", artist: "The Killers", bpm: 148, genre: "Rock", durationMinutes: 3.7, energyScore: 9 },
  { title: "Human", artist: "The Killers", bpm: 130, genre: "Rock", durationMinutes: 4.0, energyScore: 8 },
  { title: "Somebody Told Me", artist: "The Killers", bpm: 136, genre: "Rock", durationMinutes: 3.3, energyScore: 9 },
  { title: "All These Things That I've Done", artist: "The Killers", bpm: 126, genre: "Rock", durationMinutes: 5.0, energyScore: 8 },
  { title: "Smells Like Teen Spirit", artist: "Nirvana", bpm: 117, genre: "Rock", durationMinutes: 5.0, energyScore: 9 },
  { title: "Come As You Are", artist: "Nirvana", bpm: 120, genre: "Rock", durationMinutes: 3.4, energyScore: 7 },
  { title: "About a Girl", artist: "Nirvana", bpm: 100, genre: "Rock", durationMinutes: 2.8, energyScore: 7 },
  { title: "Wonderwall", artist: "Oasis", bpm: 87, genre: "Rock", durationMinutes: 4.3, energyScore: 6 },
  { title: "Don't Look Back in Anger", artist: "Oasis", bpm: 82, genre: "Rock", durationMinutes: 4.5, energyScore: 6 },
  { title: "Champagne Supernova", artist: "Oasis", bpm: 105, genre: "Rock", durationMinutes: 7.3, energyScore: 6 },
  { title: "Creep", artist: "Radiohead", bpm: 92, genre: "Rock", durationMinutes: 3.8, energyScore: 5 },
  { title: "Sweet Home Alabama", artist: "Lynyrd Skynyrd", bpm: 98, genre: "Classic Rock", durationMinutes: 4.6, energyScore: 7 },
  { title: "Free Bird", artist: "Lynyrd Skynyrd", bpm: 130, genre: "Classic Rock", durationMinutes: 9.1, energyScore: 7 },
  { title: "Hotel California", artist: "Eagles", bpm: 75, genre: "Classic Rock", durationMinutes: 6.5, energyScore: 5 },
  { title: "Take It Easy", artist: "Eagles", bpm: 138, genre: "Classic Rock", durationMinutes: 3.5, energyScore: 7 },
  { title: "Desperado", artist: "Eagles", bpm: 72, genre: "Classic Rock", durationMinutes: 3.4, energyScore: 3 },
  { title: "Life in the Fast Lane", artist: "Eagles", bpm: 132, genre: "Classic Rock", durationMinutes: 4.5, energyScore: 8 },
  { title: "Piano Man", artist: "Billy Joel", bpm: 89, genre: "Classic Rock", durationMinutes: 5.5, energyScore: 5 },
  { title: "It's Still Rock and Roll to Me", artist: "Billy Joel", bpm: 168, genre: "Classic Rock", durationMinutes: 3.3, energyScore: 8 },
  { title: "We Didn't Start the Fire", artist: "Billy Joel", bpm: 156, genre: "Classic Rock", durationMinutes: 4.9, energyScore: 8 },
  { title: "Uptown Girl", artist: "Billy Joel", bpm: 138, genre: "Classic Rock", durationMinutes: 3.3, energyScore: 8 },
  { title: "The Piano Man", artist: "Billy Joel", bpm: 89, genre: "Classic Rock", durationMinutes: 5.5, energyScore: 5 },
  { title: "Pour Some Sugar on Me", artist: "Def Leppard", bpm: 131, genre: "Rock", durationMinutes: 4.4, energyScore: 9 },
  { title: "Love Is a Battlefield", artist: "Pat Benatar", bpm: 130, genre: "Rock", durationMinutes: 4.9, energyScore: 8 },
  { title: "Hit Me with Your Best Shot", artist: "Pat Benatar", bpm: 137, genre: "Rock", durationMinutes: 3.0, energyScore: 9 },
  { title: "Heart of Glass", artist: "Blondie", bpm: 120, genre: "Rock", durationMinutes: 5.9, energyScore: 7 },
  { title: "Call Me", artist: "Blondie", bpm: 158, genre: "Rock", durationMinutes: 3.3, energyScore: 9 },
  { title: "Rock You Like a Hurricane", artist: "Scorpions", bpm: 130, genre: "Rock", durationMinutes: 4.2, energyScore: 9 },
  { title: "Wind of Change", artist: "Scorpions", bpm: 74, genre: "Rock", durationMinutes: 5.1, energyScore: 4 },
  { title: "Here I Go Again", artist: "Whitesnake", bpm: 132, genre: "Rock", durationMinutes: 4.6, energyScore: 8 },
  { title: "Eye of the Tiger", artist: "Survivor", bpm: 109, genre: "Rock", durationMinutes: 4.1, energyScore: 9 },
  { title: "Don't Stop (Thinking About Tomorrow)", artist: "Fleetwood Mac", bpm: 136, genre: "Classic Rock", durationMinutes: 3.3, energyScore: 8 },
  { title: "Go Your Own Way", artist: "Fleetwood Mac", bpm: 136, genre: "Classic Rock", durationMinutes: 3.6, energyScore: 8 },
  { title: "Dreams", artist: "Fleetwood Mac", bpm: 120, genre: "Classic Rock", durationMinutes: 4.2, energyScore: 6 },
  { title: "The Chain", artist: "Fleetwood Mac", bpm: 152, genre: "Classic Rock", durationMinutes: 4.5, energyScore: 7 },
  { title: "Gold Dust Woman", artist: "Fleetwood Mac", bpm: 94, genre: "Classic Rock", durationMinutes: 4.9, energyScore: 5 },
  { title: "Born to Run", artist: "Bruce Springsteen", bpm: 168, genre: "Classic Rock", durationMinutes: 4.5, energyScore: 9 },
  { title: "Dancing in the Dark", artist: "Bruce Springsteen", bpm: 120, genre: "Classic Rock", durationMinutes: 4.0, energyScore: 8 },
  { title: "Glory Days", artist: "Bruce Springsteen", bpm: 158, genre: "Classic Rock", durationMinutes: 4.2, energyScore: 8 },
  { title: "Pink Houses", artist: "John Mellencamp", bpm: 130, genre: "Classic Rock", durationMinutes: 4.3, energyScore: 7 },
  { title: "Jack & Diane", artist: "John Mellencamp", bpm: 120, genre: "Classic Rock", durationMinutes: 3.7, energyScore: 7 },
  { title: "Ramblin' Man", artist: "Allman Brothers Band", bpm: 132, genre: "Classic Rock", durationMinutes: 4.7, energyScore: 7 },
  { title: "Midnight Rider", artist: "Allman Brothers Band", bpm: 76, genre: "Classic Rock", durationMinutes: 3.3, energyScore: 5 },
  { title: "Black Betty", artist: "Ram Jam", bpm: 138, genre: "Classic Rock", durationMinutes: 3.2, energyScore: 9 },
  { title: "Sharp Dressed Man", artist: "ZZ Top", bpm: 130, genre: "Classic Rock", durationMinutes: 4.2, energyScore: 8 },
  { title: "Legs", artist: "ZZ Top", bpm: 126, genre: "Classic Rock", durationMinutes: 4.3, energyScore: 8 },
  { title: "La Grange", artist: "ZZ Top", bpm: 98, genre: "Classic Rock", durationMinutes: 5.4, energyScore: 7 },
  { title: "Old Time Rock and Roll", artist: "Bob Seger", bpm: 132, genre: "Classic Rock", durationMinutes: 3.3, energyScore: 8 },
  { title: "Night Moves", artist: "Bob Seger", bpm: 100, genre: "Classic Rock", durationMinutes: 5.5, energyScore: 5 },
  { title: "Turn the Page", artist: "Bob Seger", bpm: 70, genre: "Classic Rock", durationMinutes: 5.1, energyScore: 4 },
  { title: "Like a Rolling Stone", artist: "Bob Dylan", bpm: 92, genre: "Classic Rock", durationMinutes: 6.1, energyScore: 5 },
  { title: "Blowin' in the Wind", artist: "Bob Dylan", bpm: 88, genre: "Folk", durationMinutes: 2.8, energyScore: 3 },
  { title: "Mr. Tambourine Man", artist: "Bob Dylan", bpm: 90, genre: "Folk", durationMinutes: 5.6, energyScore: 3 },
  { title: "Born to Be Wild", artist: "Steppenwolf", bpm: 148, genre: "Classic Rock", durationMinutes: 3.3, energyScore: 9 },
  { title: "Magic Carpet Ride", artist: "Steppenwolf", bpm: 126, genre: "Classic Rock", durationMinutes: 4.5, energyScore: 8 },
  { title: "Fortunate Son", artist: "Creedence Clearwater Revival", bpm: 138, genre: "Classic Rock", durationMinutes: 2.3, energyScore: 8 },
  { title: "Have You Ever Seen the Rain", artist: "Creedence Clearwater Revival", bpm: 108, genre: "Classic Rock", durationMinutes: 2.6, energyScore: 6 },
  { title: "Proud Mary", artist: "Creedence Clearwater Revival", bpm: 108, genre: "Classic Rock", durationMinutes: 3.1, energyScore: 7 },
  { title: "Bad Moon Rising", artist: "Creedence Clearwater Revival", bpm: 180, genre: "Classic Rock", durationMinutes: 2.3, energyScore: 8 },
  { title: "Light My Fire", artist: "The Doors", bpm: 100, genre: "Classic Rock", durationMinutes: 7.1, energyScore: 7 },
  { title: "Riders on the Storm", artist: "The Doors", bpm: 108, genre: "Classic Rock", durationMinutes: 7.1, energyScore: 4 },
  { title: "People Are Strange", artist: "The Doors", bpm: 130, genre: "Classic Rock", durationMinutes: 2.1, energyScore: 6 },
  { title: "American Pie", artist: "Don McLean", bpm: 130, genre: "Classic Rock", durationMinutes: 8.6, energyScore: 6 },
  { title: "Vincent (Starry Starry Night)", artist: "Don McLean", bpm: 82, genre: "Folk", durationMinutes: 4.0, energyScore: 3 },
  { title: "With a Little Help from My Friends", artist: "Joe Cocker", bpm: 68, genre: "Classic Rock", durationMinutes: 5.1, energyScore: 5 },
  { title: "Unchain My Heart", artist: "Joe Cocker", bpm: 132, genre: "Classic Rock", durationMinutes: 4.2, energyScore: 7 },
  { title: "Gimme Shelter", artist: "Rolling Stones", bpm: 96, genre: "Classic Rock", durationMinutes: 4.5, energyScore: 7 },
  { title: "Paint It Black", artist: "Rolling Stones", bpm: 160, genre: "Classic Rock", durationMinutes: 3.4, energyScore: 8 },
  { title: "Wild Horses", artist: "Rolling Stones", bpm: 68, genre: "Classic Rock", durationMinutes: 5.7, energyScore: 3 },
  { title: "Sympathy for the Devil", artist: "Rolling Stones", bpm: 126, genre: "Classic Rock", durationMinutes: 6.3, energyScore: 7 },
  { title: "Start Me Up", artist: "Rolling Stones", bpm: 128, genre: "Classic Rock", durationMinutes: 3.5, energyScore: 8 },
  { title: "Jumping Jack Flash", artist: "Rolling Stones", bpm: 130, genre: "Classic Rock", durationMinutes: 3.7, energyScore: 8 },
  { title: "Brown Sugar", artist: "Rolling Stones", bpm: 150, genre: "Classic Rock", durationMinutes: 3.8, energyScore: 8 },
  { title: "Hey Jude", artist: "The Beatles", bpm: 76, genre: "Classic Rock", durationMinutes: 7.1, energyScore: 6 },
  { title: "Let It Be", artist: "The Beatles", bpm: 76, genre: "Classic Rock", durationMinutes: 4.1, energyScore: 4 },
  { title: "Come Together", artist: "The Beatles", bpm: 82, genre: "Classic Rock", durationMinutes: 4.2, energyScore: 6 },
  { title: "Twist and Shout", artist: "The Beatles", bpm: 124, genre: "Classic Rock", durationMinutes: 2.5, energyScore: 9 },
  { title: "Here Comes the Sun", artist: "The Beatles", bpm: 129, genre: "Classic Rock", durationMinutes: 3.1, energyScore: 6 },
  { title: "Blackbird", artist: "The Beatles", bpm: 94, genre: "Classic Rock", durationMinutes: 2.3, energyScore: 4 },
  { title: "Yesterday", artist: "The Beatles", bpm: 94, genre: "Classic Rock", durationMinutes: 2.1, energyScore: 2 },
  { title: "A Hard Day's Night", artist: "The Beatles", bpm: 162, genre: "Classic Rock", durationMinutes: 2.5, energyScore: 8 },
  { title: "Help!", artist: "The Beatles", bpm: 146, genre: "Classic Rock", durationMinutes: 2.3, energyScore: 7 },
  { title: "Ob-La-Di, Ob-La-Da", artist: "The Beatles", bpm: 160, genre: "Classic Rock", durationMinutes: 3.1, energyScore: 7 },
  { title: "Space Oddity", artist: "David Bowie", bpm: 72, genre: "Classic Rock", durationMinutes: 5.2, energyScore: 4 },
  { title: "Heroes", artist: "David Bowie", bpm: 116, genre: "Classic Rock", durationMinutes: 6.1, energyScore: 6 },
  { title: "Let's Dance", artist: "David Bowie", bpm: 102, genre: "Classic Rock", durationMinutes: 4.1, energyScore: 7 },
  { title: "Ziggy Stardust", artist: "David Bowie", bpm: 140, genre: "Classic Rock", durationMinutes: 3.3, energyScore: 7 },
  { title: "Changes", artist: "David Bowie", bpm: 126, genre: "Classic Rock", durationMinutes: 3.6, energyScore: 6 },
  { title: "Life on Mars?", artist: "David Bowie", bpm: 138, genre: "Classic Rock", durationMinutes: 3.5, energyScore: 5 },
  { title: "Major Tom (Coming Home)", artist: "Peter Schilling", bpm: 134, genre: "Synthpop", durationMinutes: 4.5, energyScore: 7 },
  { title: "Roxanne", artist: "The Police", bpm: 132, genre: "Rock", durationMinutes: 3.3, energyScore: 8 },
  { title: "Every Breath You Take", artist: "The Police", bpm: 116, genre: "Rock", durationMinutes: 4.1, energyScore: 5 },
  { title: "Message in a Bottle", artist: "The Police", bpm: 152, genre: "Rock", durationMinutes: 4.9, energyScore: 8 },
  { title: "Don't Stand So Close to Me", artist: "The Police", bpm: 108, genre: "Rock", durationMinutes: 4.0, energyScore: 6 },
  { title: "Should I Stay or Should I Go", artist: "The Clash", bpm: 113, genre: "Punk Rock", durationMinutes: 3.1, energyScore: 9 },
  { title: "London Calling", artist: "The Clash", bpm: 144, genre: "Punk Rock", durationMinutes: 3.2, energyScore: 8 },
  { title: "Rock the Casbah", artist: "The Clash", bpm: 160, genre: "Punk Rock", durationMinutes: 3.7, energyScore: 8 },
  { title: "Don't You (Forget About Me)", artist: "Simple Minds", bpm: 120, genre: "Rock", durationMinutes: 4.2, energyScore: 7 },
  { title: "Alive and Kicking", artist: "Simple Minds", bpm: 120, genre: "Rock", durationMinutes: 5.2, energyScore: 7 },
  { title: "With or Without You", artist: "U2", bpm: 113, genre: "Rock", durationMinutes: 4.6, energyScore: 6 },
  { title: "One", artist: "U2", bpm: 76, genre: "Rock", durationMinutes: 4.4, energyScore: 4 },
  { title: "Where the Streets Have No Name", artist: "U2", bpm: 126, genre: "Rock", durationMinutes: 5.6, energyScore: 8 },
  { title: "Sunday Bloody Sunday", artist: "U2", bpm: 130, genre: "Rock", durationMinutes: 4.4, energyScore: 7 },
  { title: "I Still Haven't Found What I'm Looking For", artist: "U2", bpm: 103, genre: "Rock", durationMinutes: 4.6, energyScore: 6 },
  { title: "Beautiful Day", artist: "U2", bpm: 137, genre: "Rock", durationMinutes: 4.1, energyScore: 8 },
  { title: "Beds Are Burning", artist: "Midnight Oil", bpm: 124, genre: "Rock", durationMinutes: 3.9, energyScore: 8 },
  { title: "Black Hole Sun", artist: "Soundgarden", bpm: 92, genre: "Grunge", durationMinutes: 5.2, energyScore: 6 },
  { title: "Spoonman", artist: "Soundgarden", bpm: 120, genre: "Grunge", durationMinutes: 4.1, energyScore: 8 },
  { title: "Jeremy", artist: "Pearl Jam", bpm: 88, genre: "Grunge", durationMinutes: 5.2, energyScore: 6 },
  { title: "Even Flow", artist: "Pearl Jam", bpm: 100, genre: "Grunge", durationMinutes: 4.9, energyScore: 7 },
  { title: "Alive", artist: "Pearl Jam", bpm: 92, genre: "Grunge", durationMinutes: 5.7, energyScore: 7 },
  { title: "Black", artist: "Pearl Jam", bpm: 72, genre: "Grunge", durationMinutes: 5.8, energyScore: 4 },
  { title: "Man in the Box", artist: "Alice in Chains", bpm: 90, genre: "Grunge", durationMinutes: 4.5, energyScore: 7 },
  { title: "Would?", artist: "Alice in Chains", bpm: 112, genre: "Grunge", durationMinutes: 3.1, energyScore: 7 },
  { title: "Plush", artist: "Stone Temple Pilots", bpm: 72, genre: "Grunge", durationMinutes: 4.2, energyScore: 5 },
  { title: "Glycerine", artist: "Bush", bpm: 70, genre: "Grunge", durationMinutes: 4.0, energyScore: 4 },
  { title: "Semi-Charmed Life", artist: "Third Eye Blind", bpm: 106, genre: "Rock", durationMinutes: 4.3, energyScore: 8 },
  { title: "How's It Going to Be", artist: "Third Eye Blind", bpm: 96, genre: "Rock", durationMinutes: 4.4, energyScore: 6 },
  { title: "Jumper", artist: "Third Eye Blind", bpm: 148, genre: "Rock", durationMinutes: 4.0, energyScore: 8 },
  { title: "Counting Blue Cars", artist: "Dishwalla", bpm: 100, genre: "Rock", durationMinutes: 5.4, energyScore: 5 },
  { title: "Closing Time", artist: "Semisonic", bpm: 120, genre: "Rock", durationMinutes: 4.4, energyScore: 6 },
  { title: "Good Riddance (Time of Your Life)", artist: "Green Day", bpm: 88, genre: "Punk Rock", durationMinutes: 2.5, energyScore: 5 },
  { title: "Basket Case", artist: "Green Day", bpm: 172, genre: "Punk Rock", durationMinutes: 3.0, energyScore: 9 },
  { title: "When I Come Around", artist: "Green Day", bpm: 100, genre: "Punk Rock", durationMinutes: 2.9, energyScore: 7 },
  { title: "Brain Stew", artist: "Green Day", bpm: 88, genre: "Punk Rock", durationMinutes: 3.2, energyScore: 7 },
  { title: "American Idiot", artist: "Green Day", bpm: 174, genre: "Punk Rock", durationMinutes: 2.9, energyScore: 9 },
  { title: "Boulevard of Broken Dreams", artist: "Green Day", bpm: 182, genre: "Punk Rock", durationMinutes: 4.2, energyScore: 6 },
  { title: "All the Small Things", artist: "blink-182", bpm: 148, genre: "Punk Pop", durationMinutes: 2.8, energyScore: 9 },
  { title: "What's My Age Again?", artist: "blink-182", bpm: 149, genre: "Punk Pop", durationMinutes: 2.5, energyScore: 9 },
  { title: "Dammit", artist: "blink-182", bpm: 155, genre: "Punk Pop", durationMinutes: 2.8, energyScore: 8 },
  { title: "Adam's Song", artist: "blink-182", bpm: 143, genre: "Punk Pop", durationMinutes: 4.8, energyScore: 5 },
  { title: "Yellow", artist: "Coldplay", bpm: 87, genre: "Rock", durationMinutes: 4.3, energyScore: 5 },
  { title: "The Scientist", artist: "Coldplay", bpm: 76, genre: "Rock", durationMinutes: 5.1, energyScore: 3 },
  { title: "Clocks", artist: "Coldplay", bpm: 131, genre: "Rock", durationMinutes: 5.1, energyScore: 7 },
  { title: "Fix You", artist: "Coldplay", bpm: 138, genre: "Rock", durationMinutes: 4.5, energyScore: 5 },
  { title: "Viva la Vida", artist: "Coldplay", bpm: 138, genre: "Rock", durationMinutes: 4.0, energyScore: 8 },
  { title: "Paradise", artist: "Coldplay", bpm: 130, genre: "Rock", durationMinutes: 4.4, energyScore: 7 },
  { title: "A Sky Full of Stars", artist: "Coldplay", bpm: 125, genre: "Rock", durationMinutes: 4.3, energyScore: 8 },
  { title: "Feel Good Inc.", artist: "Gorillaz", bpm: 139, genre: "Indie", durationMinutes: 3.8, energyScore: 7 },
  { title: "Clint Eastwood", artist: "Gorillaz", bpm: 87, genre: "Indie", durationMinutes: 5.6, energyScore: 6 },
  { title: "Chasing Cars", artist: "Snow Patrol", bpm: 104, genre: "Rock", durationMinutes: 4.3, energyScore: 4 },
  { title: "Run", artist: "Snow Patrol", bpm: 78, genre: "Rock", durationMinutes: 5.4, energyScore: 5 },
  // 80s Pop & Synthpop
  { title: "Take On Me", artist: "a-ha", bpm: 169, genre: "Synthpop", durationMinutes: 3.8, energyScore: 9 },
  { title: "Don't You Want Me", artist: "Human League", bpm: 120, genre: "Synthpop", durationMinutes: 3.9, energyScore: 8 },
  { title: "Tainted Love", artist: "Soft Cell", bpm: 123, genre: "Synthpop", durationMinutes: 2.7, energyScore: 8 },
  { title: "Come On Eileen", artist: "Dexys Midnight Runners", bpm: 115, genre: "Pop", durationMinutes: 4.3, energyScore: 9 },
  { title: "True", artist: "Spandau Ballet", bpm: 94, genre: "Synthpop", durationMinutes: 5.9, energyScore: 4 },
  { title: "Gold", artist: "Spandau Ballet", bpm: 120, genre: "Synthpop", durationMinutes: 4.9, energyScore: 7 },
  { title: "Rio", artist: "Duran Duran", bpm: 126, genre: "Synthpop", durationMinutes: 5.5, energyScore: 7 },
  { title: "Hungry Like the Wolf", artist: "Duran Duran", bpm: 136, genre: "Synthpop", durationMinutes: 3.3, energyScore: 8 },
  { title: "Girls on Film", artist: "Duran Duran", bpm: 130, genre: "Synthpop", durationMinutes: 4.3, energyScore: 8 },
  { title: "Fade to Grey", artist: "Visage", bpm: 118, genre: "Synthpop", durationMinutes: 4.4, energyScore: 6 },
  { title: "Mad World", artist: "Tears for Fears", bpm: 90, genre: "Synthpop", durationMinutes: 3.3, energyScore: 3 },
  { title: "Shout", artist: "Tears for Fears", bpm: 95, genre: "Synthpop", durationMinutes: 5.2, energyScore: 6 },
  { title: "Everybody Wants to Rule the World", artist: "Tears for Fears", bpm: 122, genre: "Synthpop", durationMinutes: 4.2, energyScore: 7 },
  { title: "Head Over Heels", artist: "Tears for Fears", bpm: 120, genre: "Synthpop", durationMinutes: 4.1, energyScore: 7 },
  { title: "Midnight City", artist: "M83", bpm: 105, genre: "Synthpop", durationMinutes: 4.0, energyScore: 7 },
  { title: "Blinding Lights", artist: "The Weeknd", bpm: 171, genre: "Synthpop", durationMinutes: 3.4, energyScore: 9 },
  { title: "Save Your Tears", artist: "The Weeknd", bpm: 118, genre: "Synthpop", durationMinutes: 3.5, energyScore: 8 },
  { title: "Blue (Da Ba Dee)", artist: "Eiffel 65", bpm: 138, genre: "Eurodance", durationMinutes: 3.6, energyScore: 9 },
  { title: "Rhythm Is a Dancer", artist: "Snap!", bpm: 130, genre: "Eurodance", durationMinutes: 4.1, energyScore: 9 },
  { title: "What Is Love", artist: "Haddaway", bpm: 118, genre: "Eurodance", durationMinutes: 3.8, energyScore: 9 },
  { title: "Gonna Make You Sweat (Everybody Dance Now)", artist: "C+C Music Factory", bpm: 130, genre: "Dance", durationMinutes: 4.0, energyScore: 9 },
  { title: "Venus", artist: "Bananarama", bpm: 120, genre: "Pop", durationMinutes: 3.8, energyScore: 8 },
  { title: "Cruel Summer", artist: "Bananarama", bpm: 132, genre: "Pop", durationMinutes: 3.3, energyScore: 8 },
  { title: "Girls Just Want to Have Fun", artist: "Cyndi Lauper", bpm: 120, genre: "Pop", durationMinutes: 3.9, energyScore: 8 },
  { title: "Time After Time", artist: "Cyndi Lauper", bpm: 89, genre: "Pop", durationMinutes: 4.0, energyScore: 4 },
  { title: "True Colors", artist: "Cyndi Lauper", bpm: 72, genre: "Pop", durationMinutes: 3.8, energyScore: 3 },
  { title: "Walking on Sunshine", artist: "Katrina and The Waves", bpm: 103, genre: "Pop", durationMinutes: 3.6, energyScore: 9 },
  { title: "Don't Stop Me Now", artist: "Queen", bpm: 156, genre: "Rock", durationMinutes: 3.6, energyScore: 10 },
  { title: "Wake Me Up Before You Go-Go", artist: "Wham!", bpm: 156, genre: "Pop", durationMinutes: 3.5, energyScore: 9 },
  { title: "Careless Whisper", artist: "George Michael", bpm: 108, genre: "Pop", durationMinutes: 5.1, energyScore: 4 },
  { title: "Faith", artist: "George Michael", bpm: 130, genre: "Pop", durationMinutes: 3.3, energyScore: 8 },
  { title: "Father Figure", artist: "George Michael", bpm: 92, genre: "Pop", durationMinutes: 5.5, energyScore: 5 },
  { title: "Somebody to Love", artist: "Whitney Houston", bpm: 76, genre: "R&B", durationMinutes: 4.5, energyScore: 7 },
  { title: "I Wanna Dance with Somebody", artist: "Whitney Houston", bpm: 118, genre: "Pop", durationMinutes: 4.9, energyScore: 8 },
  { title: "Greatest Love of All", artist: "Whitney Houston", bpm: 62, genre: "Pop", durationMinutes: 4.9, energyScore: 5 },
  { title: "I Will Always Love You", artist: "Whitney Houston", bpm: 66, genre: "Pop", durationMinutes: 4.5, energyScore: 6 },
  { title: "Run to You", artist: "Whitney Houston", bpm: 106, genre: "Pop", durationMinutes: 3.7, energyScore: 7 },
  { title: "Saving All My Love for You", artist: "Whitney Houston", bpm: 90, genre: "Pop", durationMinutes: 3.9, energyScore: 5 },
  { title: "Like a Prayer", artist: "Madonna", bpm: 126, genre: "Pop", durationMinutes: 5.4, energyScore: 8 },
  { title: "Material Girl", artist: "Madonna", bpm: 128, genre: "Pop", durationMinutes: 3.9, energyScore: 8 },
  { title: "Papa Don't Preach", artist: "Madonna", bpm: 118, genre: "Pop", durationMinutes: 4.5, energyScore: 7 },
  { title: "Like a Virgin", artist: "Madonna", bpm: 116, genre: "Pop", durationMinutes: 3.6, energyScore: 7 },
  { title: "Holiday", artist: "Madonna", bpm: 126, genre: "Pop", durationMinutes: 6.2, energyScore: 8 },
  { title: "Vogue", artist: "Madonna", bpm: 132, genre: "Pop", durationMinutes: 5.0, energyScore: 9 },
  { title: "Into the Groove", artist: "Madonna", bpm: 128, genre: "Pop", durationMinutes: 4.6, energyScore: 9 },
  { title: "Physical", artist: "Olivia Newton-John", bpm: 126, genre: "Pop", durationMinutes: 3.7, energyScore: 8 },
  { title: "Hopelessly Devoted to You", artist: "Olivia Newton-John", bpm: 65, genre: "Pop", durationMinutes: 3.6, energyScore: 3 },
  { title: "Xanadu", artist: "Olivia Newton-John", bpm: 135, genre: "Pop", durationMinutes: 3.5, energyScore: 7 },
  // Disco
  { title: "Dancing Queen", artist: "ABBA", bpm: 101, genre: "Pop", durationMinutes: 3.8, energyScore: 8 },
  { title: "Waterloo", artist: "ABBA", bpm: 168, genre: "Pop", durationMinutes: 2.4, energyScore: 9 },
  { title: "Mamma Mia", artist: "ABBA", bpm: 138, genre: "Pop", durationMinutes: 3.5, energyScore: 8 },
  { title: "The Winner Takes It All", artist: "ABBA", bpm: 63, genre: "Pop", durationMinutes: 4.9, energyScore: 4 },
  { title: "Fernando", artist: "ABBA", bpm: 84, genre: "Pop", durationMinutes: 4.2, energyScore: 4 },
  { title: "Gimme! Gimme! Gimme!", artist: "ABBA", bpm: 126, genre: "Disco", durationMinutes: 4.9, energyScore: 8 },
  { title: "Voulez-Vous", artist: "ABBA", bpm: 130, genre: "Disco", durationMinutes: 5.1, energyScore: 8 },
  { title: "I Will Survive", artist: "Gloria Gaynor", bpm: 117, genre: "Disco", durationMinutes: 4.9, energyScore: 8 },
  { title: "Never Can Say Goodbye", artist: "Gloria Gaynor", bpm: 124, genre: "Disco", durationMinutes: 3.2, energyScore: 7 },
  { title: "September", artist: "Earth, Wind & Fire", bpm: 126, genre: "R&B", durationMinutes: 3.6, energyScore: 9 },
  { title: "Boogie Wonderland", artist: "Earth, Wind & Fire", bpm: 123, genre: "Disco", durationMinutes: 4.6, energyScore: 9 },
  { title: "Let's Groove", artist: "Earth, Wind & Fire", bpm: 100, genre: "R&B", durationMinutes: 5.5, energyScore: 8 },
  { title: "Shining Star", artist: "Earth, Wind & Fire", bpm: 105, genre: "R&B", durationMinutes: 2.5, energyScore: 8 },
  { title: "Got to Be Real", artist: "Cheryl Lynn", bpm: 112, genre: "Disco", durationMinutes: 5.3, energyScore: 8 },
  { title: "Last Dance", artist: "Donna Summer", bpm: 124, genre: "Disco", durationMinutes: 7.7, energyScore: 8 },
  { title: "Hot Stuff", artist: "Donna Summer", bpm: 112, genre: "Disco", durationMinutes: 5.1, energyScore: 9 },
  { title: "Bad Girls", artist: "Donna Summer", bpm: 120, genre: "Disco", durationMinutes: 4.9, energyScore: 9 },
  { title: "Le Freak", artist: "Chic", bpm: 124, genre: "Disco", durationMinutes: 3.4, energyScore: 9 },
  { title: "Good Times", artist: "Chic", bpm: 108, genre: "Disco", durationMinutes: 8.5, energyScore: 8 },
  { title: "Funkytown", artist: "Lipps Inc", bpm: 120, genre: "Disco", durationMinutes: 4.2, energyScore: 9 },
  { title: "We Are Family", artist: "Sister Sledge", bpm: 122, genre: "Disco", durationMinutes: 3.3, energyScore: 9 },
  { title: "He's the Greatest Dancer", artist: "Sister Sledge", bpm: 116, genre: "Disco", durationMinutes: 5.3, energyScore: 8 },
  { title: "Staying Alive", artist: "Bee Gees", bpm: 104, genre: "Disco", durationMinutes: 4.5, energyScore: 8 },
  { title: "Night Fever", artist: "Bee Gees", bpm: 110, genre: "Disco", durationMinutes: 3.6, energyScore: 8 },
  { title: "How Deep Is Your Love", artist: "Bee Gees", bpm: 86, genre: "Disco", durationMinutes: 3.9, energyScore: 4 },
  { title: "More Than a Woman", artist: "Bee Gees", bpm: 108, genre: "Disco", durationMinutes: 3.3, energyScore: 7 },
  { title: "You Should Be Dancing", artist: "Bee Gees", bpm: 108, genre: "Disco", durationMinutes: 4.7, energyScore: 9 },
  // Country
  { title: "Take Me Home, Country Roads", artist: "John Denver", bpm: 84, genre: "Country", durationMinutes: 3.8, energyScore: 7 },
  { title: "Jolene", artist: "Dolly Parton", bpm: 80, genre: "Country", durationMinutes: 2.7, energyScore: 5 },
  { title: "9 to 5", artist: "Dolly Parton", bpm: 178, genre: "Country", durationMinutes: 2.7, energyScore: 9 },
  { title: "I Will Always Love You", artist: "Dolly Parton", bpm: 70, genre: "Country", durationMinutes: 2.7, energyScore: 5 },
  { title: "Coat of Many Colors", artist: "Dolly Parton", bpm: 136, genre: "Country", durationMinutes: 2.7, energyScore: 6 },
  { title: "Friends in Low Places", artist: "Garth Brooks", bpm: 136, genre: "Country", durationMinutes: 4.2, energyScore: 8 },
  { title: "The Dance", artist: "Garth Brooks", bpm: 80, genre: "Country", durationMinutes: 3.5, energyScore: 4 },
  { title: "Unanswered Prayers", artist: "Garth Brooks", bpm: 72, genre: "Country", durationMinutes: 3.7, energyScore: 3 },
  { title: "Shameless", artist: "Garth Brooks", bpm: 90, genre: "Country", durationMinutes: 3.8, energyScore: 6 },
  { title: "Achy Breaky Heart", artist: "Billy Ray Cyrus", bpm: 136, genre: "Country", durationMinutes: 3.3, energyScore: 8 },
  { title: "Boot Scootin' Boogie", artist: "Brooks & Dunn", bpm: 142, genre: "Country", durationMinutes: 3.4, energyScore: 8 },
  { title: "Neon Moon", artist: "Brooks & Dunn", bpm: 78, genre: "Country", durationMinutes: 4.0, energyScore: 4 },
  { title: "Redneck Woman", artist: "Gretchen Wilson", bpm: 156, genre: "Country", durationMinutes: 3.6, energyScore: 9 },
  { title: "Before He Cheats", artist: "Carrie Underwood", bpm: 148, genre: "Country", durationMinutes: 3.8, energyScore: 8 },
  { title: "Jesus, Take the Wheel", artist: "Carrie Underwood", bpm: 78, genre: "Country", durationMinutes: 3.6, energyScore: 4 },
  { title: "Blown Away", artist: "Carrie Underwood", bpm: 128, genre: "Country", durationMinutes: 3.9, energyScore: 7 },
  { title: "Something in the Water", artist: "Carrie Underwood", bpm: 130, genre: "Country", durationMinutes: 4.0, energyScore: 7 },
  { title: "Need You Now", artist: "Lady A", bpm: 86, genre: "Country", durationMinutes: 3.5, energyScore: 5 },
  { title: "American Honey", artist: "Lady A", bpm: 84, genre: "Country", durationMinutes: 4.4, energyScore: 5 },
  { title: "I Hope You Dance", artist: "Lee Ann Womack", bpm: 89, genre: "Country", durationMinutes: 4.3, energyScore: 4 },
  { title: "Keeper of the Stars", artist: "Tracy Byrd", bpm: 68, genre: "Country", durationMinutes: 3.8, energyScore: 2 },
  { title: "Whiskey Lullaby", artist: "Brad Paisley", bpm: 72, genre: "Country", durationMinutes: 4.6, energyScore: 3 },
  { title: "He Didn't Have to Be", artist: "Brad Paisley", bpm: 80, genre: "Country", durationMinutes: 4.0, energyScore: 4 },
  { title: "Online", artist: "Brad Paisley", bpm: 148, genre: "Country", durationMinutes: 3.7, energyScore: 8 },
  { title: "Letter to Me", artist: "Brad Paisley", bpm: 92, genre: "Country", durationMinutes: 4.1, energyScore: 5 },
  { title: "I'm Gonna Miss Her", artist: "Brad Paisley", bpm: 132, genre: "Country", durationMinutes: 3.2, energyScore: 7 },
  { title: "Cruise", artist: "Florida Georgia Line", bpm: 116, genre: "Country", durationMinutes: 3.9, energyScore: 7 },
  { title: "This Is How We Roll", artist: "Florida Georgia Line", bpm: 136, genre: "Country", durationMinutes: 3.6, energyScore: 8 },
  { title: "Die a Happy Man", artist: "Thomas Rhett", bpm: 80, genre: "Country", durationMinutes: 3.5, energyScore: 4 },
  { title: "Unforgettable", artist: "Thomas Rhett", bpm: 80, genre: "Country", durationMinutes: 4.3, energyScore: 5 },
  { title: "Meant to Be", artist: "Bebe Rexha & Florida Georgia Line", bpm: 102, genre: "Country Pop", durationMinutes: 3.4, energyScore: 6 },
  { title: "Tennessee Whiskey", artist: "Chris Stapleton", bpm: 62, genre: "Country", durationMinutes: 4.5, energyScore: 5 },
  { title: "Broken Halos", artist: "Chris Stapleton", bpm: 74, genre: "Country", durationMinutes: 4.0, energyScore: 4 },
  { title: "Millionaire", artist: "Chris Stapleton", bpm: 80, genre: "Country", durationMinutes: 3.7, energyScore: 5 },
  { title: "Body Like a Back Road", artist: "Sam Hunt", bpm: 92, genre: "Country Pop", durationMinutes: 3.3, energyScore: 6 },
  { title: "Leave the Night On", artist: "Sam Hunt", bpm: 128, genre: "Country Pop", durationMinutes: 3.4, energyScore: 7 },
  { title: "Drunk Me", artist: "Mitchell Tenpenny", bpm: 90, genre: "Country", durationMinutes: 3.5, energyScore: 6 },
  { title: "Girl Crush", artist: "Little Big Town", bpm: 72, genre: "Country", durationMinutes: 4.0, energyScore: 3 },
  { title: "Better Man", artist: "Little Big Town", bpm: 68, genre: "Country", durationMinutes: 4.3, energyScore: 3 },
  { title: "Pontoon", artist: "Little Big Town", bpm: 128, genre: "Country", durationMinutes: 3.8, energyScore: 8 },
  { title: "Chicken Fried", artist: "Zac Brown Band", bpm: 100, genre: "Country", durationMinutes: 5.2, energyScore: 7 },
  { title: "Colder Weather", artist: "Zac Brown Band", bpm: 80, genre: "Country", durationMinutes: 5.3, energyScore: 4 },
  { title: "Knee Deep", artist: "Zac Brown Band", bpm: 96, genre: "Country", durationMinutes: 5.8, energyScore: 6 },
  { title: "Old Town Road", artist: "Lil Nas X", bpm: 136, genre: "Country Trap", durationMinutes: 1.9, energyScore: 8 },
  { title: "Love Story (Taylor's Version)", artist: "Taylor Swift", bpm: 119, genre: "Country Pop", durationMinutes: 3.9, energyScore: 7 },
  { title: "You Belong With Me", artist: "Taylor Swift", bpm: 130, genre: "Country Pop", durationMinutes: 3.9, energyScore: 8 },
  // R&B & Soul
  { title: "Killing Me Softly", artist: "Fugees", bpm: 90, genre: "R&B", durationMinutes: 5.1, energyScore: 4 },
  { title: "No Diggity", artist: "Blackstreet", bpm: 97, genre: "R&B", durationMinutes: 4.6, energyScore: 7 },
  { title: "Waterfalls", artist: "TLC", bpm: 96, genre: "R&B", durationMinutes: 4.4, energyScore: 5 },
  { title: "Creep (TLC)", artist: "TLC", bpm: 92, genre: "R&B", durationMinutes: 4.4, energyScore: 5 },
  { title: "No Scrubs", artist: "TLC", bpm: 100, genre: "R&B", durationMinutes: 3.5, energyScore: 7 },
  { title: "Crazy in Love", artist: "Beyoncé", bpm: 99, genre: "R&B", durationMinutes: 3.9, energyScore: 9 },
  { title: "Single Ladies", artist: "Beyoncé", bpm: 97, genre: "R&B", durationMinutes: 3.2, energyScore: 8 },
  { title: "Halo", artist: "Beyoncé", bpm: 84, genre: "R&B", durationMinutes: 4.4, energyScore: 5 },
  { title: "Love on Top", artist: "Beyoncé", bpm: 113, genre: "R&B", durationMinutes: 4.0, energyScore: 8 },
  { title: "Irreplaceable", artist: "Beyoncé", bpm: 98, genre: "R&B", durationMinutes: 3.8, energyScore: 7 },
  { title: "Drunk in Love", artist: "Beyoncé", bpm: 130, genre: "R&B", durationMinutes: 5.4, energyScore: 7 },
  { title: "When Doves Cry", artist: "Prince", bpm: 121, genre: "R&B", durationMinutes: 5.5, energyScore: 8 },
  { title: "Purple Rain", artist: "Prince", bpm: 113, genre: "R&B", durationMinutes: 8.4, energyScore: 5 },
  { title: "Kiss", artist: "Prince", bpm: 111, genre: "Funk", durationMinutes: 3.6, energyScore: 8 },
  { title: "Let's Go Crazy", artist: "Prince", bpm: 167, genre: "Funk Rock", durationMinutes: 4.7, energyScore: 9 },
  { title: "Raspberry Beret", artist: "Prince", bpm: 117, genre: "Funk", durationMinutes: 3.9, energyScore: 7 },
  { title: "Sign 'O' the Times", artist: "Prince", bpm: 91, genre: "R&B", durationMinutes: 4.9, energyScore: 6 },
  { title: "U Got the Look", artist: "Prince", bpm: 135, genre: "R&B", durationMinutes: 3.5, energyScore: 8 },
  { title: "End of the Road", artist: "Boyz II Men", bpm: 68, genre: "R&B", durationMinutes: 5.0, energyScore: 2 },
  { title: "I'll Make Love to You", artist: "Boyz II Men", bpm: 64, genre: "R&B", durationMinutes: 3.9, energyScore: 2 },
  { title: "Motownphilly", artist: "Boyz II Men", bpm: 96, genre: "R&B", durationMinutes: 4.6, energyScore: 7 },
  { title: "One Sweet Day", artist: "Mariah Carey & Boyz II Men", bpm: 68, genre: "R&B", durationMinutes: 4.4, energyScore: 3 },
  { title: "Hero", artist: "Mariah Carey", bpm: 63, genre: "Pop", durationMinutes: 4.5, energyScore: 4 },
  { title: "Always Be My Baby", artist: "Mariah Carey", bpm: 95, genre: "R&B", durationMinutes: 4.2, energyScore: 6 },
  { title: "Emotions", artist: "Mariah Carey", bpm: 101, genre: "R&B", durationMinutes: 4.5, energyScore: 8 },
  { title: "We Belong Together", artist: "Mariah Carey", bpm: 68, genre: "R&B", durationMinutes: 3.6, energyScore: 4 },
  { title: "Fantasy", artist: "Mariah Carey", bpm: 96, genre: "R&B", durationMinutes: 4.1, energyScore: 7 },
  { title: "All I Want for Christmas Is You", artist: "Mariah Carey", bpm: 151, genre: "Holiday", durationMinutes: 4.0, energyScore: 8 },
  { title: "Respect", artist: "Aretha Franklin", bpm: 114, genre: "Soul", durationMinutes: 2.9, energyScore: 9 },
  { title: "Natural Woman", artist: "Aretha Franklin", bpm: 74, genre: "Soul", durationMinutes: 3.0, energyScore: 5 },
  { title: "Think", artist: "Aretha Franklin", bpm: 126, genre: "Soul", durationMinutes: 2.9, energyScore: 8 },
  { title: "Chain of Fools", artist: "Aretha Franklin", bpm: 116, genre: "Soul", durationMinutes: 2.5, energyScore: 8 },
  { title: "I Say a Little Prayer", artist: "Aretha Franklin", bpm: 130, genre: "Soul", durationMinutes: 3.5, energyScore: 7 },
  { title: "Superstition", artist: "Stevie Wonder", bpm: 98, genre: "Soul", durationMinutes: 4.0, energyScore: 9 },
  { title: "Signed, Sealed, Delivered I'm Yours", artist: "Stevie Wonder", bpm: 120, genre: "Soul", durationMinutes: 2.7, energyScore: 8 },
  { title: "Sir Duke", artist: "Stevie Wonder", bpm: 95, genre: "Soul", durationMinutes: 3.8, energyScore: 9 },
  { title: "Higher Ground", artist: "Stevie Wonder", bpm: 138, genre: "Soul", durationMinutes: 3.5, energyScore: 9 },
  { title: "Isn't She Lovely", artist: "Stevie Wonder", bpm: 108, genre: "Soul", durationMinutes: 6.3, energyScore: 7 },
  { title: "I Just Called to Say I Love You", artist: "Stevie Wonder", bpm: 100, genre: "Soul", durationMinutes: 4.4, energyScore: 5 },
  { title: "Happy Birthday", artist: "Stevie Wonder", bpm: 100, genre: "Soul", durationMinutes: 5.0, energyScore: 7 },
  { title: "Let's Stay Together", artist: "Al Green", bpm: 76, genre: "Soul", durationMinutes: 3.2, energyScore: 5 },
  { title: "Tired of Being Alone", artist: "Al Green", bpm: 83, genre: "Soul", durationMinutes: 2.5, energyScore: 5 },
  { title: "What's Going On", artist: "Marvin Gaye", bpm: 99, genre: "Soul", durationMinutes: 3.8, energyScore: 5 },
  { title: "Sexual Healing", artist: "Marvin Gaye", bpm: 100, genre: "Soul", durationMinutes: 4.3, energyScore: 6 },
  { title: "Let's Get It On", artist: "Marvin Gaye", bpm: 96, genre: "Soul", durationMinutes: 4.8, energyScore: 5 },
  { title: "Heard It Through the Grapevine", artist: "Marvin Gaye", bpm: 104, genre: "Soul", durationMinutes: 3.2, energyScore: 6 },
  { title: "I Can't Help Myself (Sugar Pie Honey Bunch)", artist: "Four Tops", bpm: 128, genre: "Soul", durationMinutes: 2.5, energyScore: 8 },
  { title: "My Girl", artist: "The Temptations", bpm: 100, genre: "Soul", durationMinutes: 2.9, energyScore: 6 },
  { title: "Papa Was a Rollin' Stone", artist: "The Temptations", bpm: 90, genre: "Soul", durationMinutes: 7.0, energyScore: 5 },
  { title: "Ain't Too Proud to Beg", artist: "The Temptations", bpm: 120, genre: "Soul", durationMinutes: 2.7, energyScore: 7 },
  { title: "I Heard It Through the Grapevine", artist: "The Temptations", bpm: 104, genre: "Soul", durationMinutes: 2.9, energyScore: 7 },
  { title: "Stop! In the Name of Love", artist: "The Supremes", bpm: 112, genre: "Soul", durationMinutes: 2.8, energyScore: 7 },
  { title: "You Can't Hurry Love", artist: "The Supremes", bpm: 132, genre: "Soul", durationMinutes: 2.5, energyScore: 8 },
  { title: "Baby Love", artist: "The Supremes", bpm: 112, genre: "Soul", durationMinutes: 2.6, energyScore: 7 },
  { title: "Smooth Criminal", artist: "Michael Jackson", bpm: 118, genre: "Pop", durationMinutes: 4.1, energyScore: 9 },
  { title: "Billie Jean", artist: "Michael Jackson", bpm: 117, genre: "Pop", durationMinutes: 4.9, energyScore: 8 },
  { title: "Beat It", artist: "Michael Jackson", bpm: 138, genre: "Pop", durationMinutes: 4.2, energyScore: 9 },
  { title: "Thriller", artist: "Michael Jackson", bpm: 118, genre: "Pop", durationMinutes: 5.6, energyScore: 8 },
  { title: "Don't Stop 'Til You Get Enough", artist: "Michael Jackson", bpm: 113, genre: "Funk", durationMinutes: 6.1, energyScore: 9 },
  { title: "Rock with You", artist: "Michael Jackson", bpm: 113, genre: "Funk", durationMinutes: 3.7, energyScore: 8 },
  { title: "P.Y.T. (Pretty Young Thing)", artist: "Michael Jackson", bpm: 108, genre: "Pop", durationMinutes: 4.0, energyScore: 8 },
  { title: "Man in the Mirror", artist: "Michael Jackson", bpm: 100, genre: "Pop", durationMinutes: 5.2, energyScore: 7 },
  { title: "Black or White", artist: "Michael Jackson", bpm: 116, genre: "Pop", durationMinutes: 4.2, energyScore: 8 },
  { title: "Umbrella", artist: "Rihanna", bpm: 130, genre: "Pop", durationMinutes: 4.3, energyScore: 8 },
  { title: "We Found Love", artist: "Rihanna", bpm: 128, genre: "Pop", durationMinutes: 3.6, energyScore: 9 },
  { title: "Diamonds", artist: "Rihanna", bpm: 125, genre: "Pop", durationMinutes: 3.8, energyScore: 6 },
  { title: "Stay", artist: "Rihanna", bpm: 128, genre: "Pop", durationMinutes: 4.0, energyScore: 4 },
  { title: "Work", artist: "Rihanna", bpm: 97, genre: "R&B", durationMinutes: 3.7, energyScore: 7 },
  { title: "Positions", artist: "Ariana Grande", bpm: 144, genre: "R&B", durationMinutes: 2.9, energyScore: 7 },
  { title: "7 rings", artist: "Ariana Grande", bpm: 140, genre: "Pop", durationMinutes: 2.9, energyScore: 8 },
  { title: "thank u, next", artist: "Ariana Grande", bpm: 107, genre: "Pop", durationMinutes: 3.4, energyScore: 7 },
  { title: "Problem", artist: "Ariana Grande", bpm: 126, genre: "Pop", durationMinutes: 3.5, energyScore: 8 },
  { title: "Into You", artist: "Ariana Grande", bpm: 126, genre: "Pop", durationMinutes: 4.0, energyScore: 8 },
  { title: "Break Free", artist: "Ariana Grande", bpm: 130, genre: "Pop", durationMinutes: 3.3, energyScore: 8 },
  { title: "No Tears Left to Cry", artist: "Ariana Grande", bpm: 86, genre: "Pop", durationMinutes: 3.4, energyScore: 7 },
  // Hip Hop
  { title: "Baby Got Back", artist: "Sir Mix-a-Lot", bpm: 134, genre: "Hip Hop", durationMinutes: 4.2, energyScore: 9 },
  { title: "Lose Yourself", artist: "Eminem", bpm: 86, genre: "Hip Hop", durationMinutes: 5.3, energyScore: 8 },
  { title: "Without Me", artist: "Eminem", bpm: 88, genre: "Hip Hop", durationMinutes: 4.8, energyScore: 8 },
  { title: "The Real Slim Shady", artist: "Eminem", bpm: 104, genre: "Hip Hop", durationMinutes: 4.4, energyScore: 8 },
  { title: "Rap God", artist: "Eminem", bpm: 136, genre: "Hip Hop", durationMinutes: 6.1, energyScore: 9 },
  { title: "Gold Digger", artist: "Kanye West", bpm: 112, genre: "Hip Hop", durationMinutes: 3.3, energyScore: 8 },
  { title: "All Falls Down", artist: "Kanye West", bpm: 98, genre: "Hip Hop", durationMinutes: 3.3, energyScore: 7 },
  { title: "Stronger", artist: "Kanye West", bpm: 106, genre: "Hip Hop", durationMinutes: 5.1, energyScore: 8 },
  { title: "Hotline Bling", artist: "Drake", bpm: 135, genre: "Hip Hop", durationMinutes: 4.3, energyScore: 7 },
  { title: "One Dance", artist: "Drake", bpm: 104, genre: "Hip Hop", durationMinutes: 2.5, energyScore: 7 },
  { title: "God's Plan", artist: "Drake", bpm: 77, genre: "Hip Hop", durationMinutes: 3.2, energyScore: 6 },
  { title: "In My Feelings", artist: "Drake", bpm: 125, genre: "Hip Hop", durationMinutes: 3.3, energyScore: 7 },
  { title: "WAP", artist: "Cardi B", bpm: 131, genre: "Hip Hop", durationMinutes: 3.2, energyScore: 9 },
  { title: "Bodak Yellow", artist: "Cardi B", bpm: 80, genre: "Hip Hop", durationMinutes: 3.5, energyScore: 8 },
  { title: "INDUSTRY BABY", artist: "Lil Nas X", bpm: 149, genre: "Pop", durationMinutes: 3.3, energyScore: 9 },
  { title: "Fancy", artist: "Iggy Azalea", bpm: 115, genre: "Hip Hop", durationMinutes: 3.8, energyScore: 8 },
  { title: "Boom", artist: "Iggy Azalea", bpm: 130, genre: "Hip Hop", durationMinutes: 3.0, energyScore: 8 },
  { title: "No Scrubs (TLC)", artist: "TLC", bpm: 100, genre: "R&B", durationMinutes: 3.5, energyScore: 7 },
  { title: "Lean On", artist: "Major Lazer", bpm: 98, genre: "Electronic", durationMinutes: 2.8, energyScore: 8 },
  { title: "Royals", artist: "Lorde", bpm: 86, genre: "Indie Pop", durationMinutes: 3.1, energyScore: 5 },
  { title: "Tennis Court", artist: "Lorde", bpm: 100, genre: "Indie Pop", durationMinutes: 3.9, energyScore: 6 },
  { title: "Team", artist: "Lorde", bpm: 116, genre: "Indie Pop", durationMinutes: 3.0, energyScore: 6 },
  { title: "Green Light", artist: "Lorde", bpm: 127, genre: "Indie Pop", durationMinutes: 3.5, energyScore: 7 },
  // Pop Hits
  { title: "Sweet Caroline", artist: "Neil Diamond", bpm: 121, genre: "Pop", durationMinutes: 3.6, energyScore: 8 },
  { title: "Cherry Cherry", artist: "Neil Diamond", bpm: 140, genre: "Pop", durationMinutes: 2.8, energyScore: 8 },
  { title: "Total Eclipse of the Heart", artist: "Bonnie Tyler", bpm: 90, genre: "Pop", durationMinutes: 5.6, energyScore: 7 },
  { title: "Holding Out for a Hero", artist: "Bonnie Tyler", bpm: 148, genre: "Pop", durationMinutes: 5.0, energyScore: 9 },
  { title: "Africa", artist: "Toto", bpm: 92, genre: "Pop", durationMinutes: 4.9, energyScore: 6 },
  { title: "Rosanna", artist: "Toto", bpm: 97, genre: "Pop", durationMinutes: 5.3, energyScore: 7 },
  { title: "Somebody That I Used to Know", artist: "Gotye", bpm: 129, genre: "Indie", durationMinutes: 4.1, energyScore: 6 },
  { title: "Shallow", artist: "Lady Gaga & Bradley Cooper", bpm: 96, genre: "Pop", durationMinutes: 3.6, energyScore: 7 },
  { title: "Fast Car", artist: "Tracy Chapman", bpm: 102, genre: "Folk", durationMinutes: 4.9, energyScore: 6 },
  { title: "Give Me One Reason", artist: "Tracy Chapman", bpm: 88, genre: "Folk", durationMinutes: 4.0, energyScore: 6 },
  { title: "Bad Romance", artist: "Lady Gaga", bpm: 119, genre: "Pop", durationMinutes: 4.9, energyScore: 9 },
  { title: "Poker Face", artist: "Lady Gaga", bpm: 120, genre: "Pop", durationMinutes: 3.6, energyScore: 8 },
  { title: "Just Dance", artist: "Lady Gaga", bpm: 119, genre: "Pop", durationMinutes: 4.1, energyScore: 9 },
  { title: "Edge of Glory", artist: "Lady Gaga", bpm: 130, genre: "Pop", durationMinutes: 5.2, energyScore: 8 },
  { title: "Rolling in the Deep", artist: "Adele", bpm: 105, genre: "Pop", durationMinutes: 3.8, energyScore: 8 },
  { title: "Someone Like You", artist: "Adele", bpm: 68, genre: "Pop", durationMinutes: 4.8, energyScore: 3 },
  { title: "Hello", artist: "Adele", bpm: 79, genre: "Pop", durationMinutes: 4.6, energyScore: 4 },
  { title: "Set Fire to the Rain", artist: "Adele", bpm: 108, genre: "Pop", durationMinutes: 4.0, energyScore: 7 },
  { title: "Skyfall", artist: "Adele", bpm: 73, genre: "Pop", durationMinutes: 4.5, energyScore: 5 },
  { title: "Easy On Me", artist: "Adele", bpm: 72, genre: "Pop", durationMinutes: 3.4, energyScore: 3 },
  { title: "Shape of You", artist: "Ed Sheeran", bpm: 96, genre: "Pop", durationMinutes: 3.9, energyScore: 7 },
  { title: "Thinking Out Loud", artist: "Ed Sheeran", bpm: 79, genre: "Pop", durationMinutes: 4.7, energyScore: 3 },
  { title: "Perfect", artist: "Ed Sheeran", bpm: 95, genre: "Pop", durationMinutes: 4.6, energyScore: 4 },
  { title: "Photograph", artist: "Ed Sheeran", bpm: 108, genre: "Pop", durationMinutes: 4.2, energyScore: 5 },
  { title: "Galway Girl", artist: "Ed Sheeran", bpm: 100, genre: "Pop", durationMinutes: 2.8, energyScore: 8 },
  { title: "Castle on the Hill", artist: "Ed Sheeran", bpm: 135, genre: "Pop", durationMinutes: 4.2, energyScore: 8 },
  { title: "Toxic", artist: "Britney Spears", bpm: 143, genre: "Pop", durationMinutes: 3.3, energyScore: 9 },
  { title: "Baby One More Time", artist: "Britney Spears", bpm: 96, genre: "Pop", durationMinutes: 3.3, energyScore: 8 },
  { title: "Oops!... I Did It Again", artist: "Britney Spears", bpm: 96, genre: "Pop", durationMinutes: 3.3, energyScore: 8 },
  { title: "Womanizer", artist: "Britney Spears", bpm: 137, genre: "Pop", durationMinutes: 3.4, energyScore: 8 },
  { title: "Levitating", artist: "Dua Lipa", bpm: 103, genre: "Pop", durationMinutes: 3.5, energyScore: 8 },
  { title: "Don't Start Now", artist: "Dua Lipa", bpm: 124, genre: "Pop", durationMinutes: 3.4, energyScore: 9 },
  { title: "Physical", artist: "Dua Lipa", bpm: 124, genre: "Pop", durationMinutes: 3.4, energyScore: 9 },
  { title: "New Rules", artist: "Dua Lipa", bpm: 116, genre: "Pop", durationMinutes: 3.6, energyScore: 8 },
  { title: "As It Was", artist: "Harry Styles", bpm: 174, genre: "Pop", durationMinutes: 2.6, energyScore: 8 },
  { title: "Watermelon Sugar", artist: "Harry Styles", bpm: 95, genre: "Pop", durationMinutes: 2.9, energyScore: 7 },
  { title: "Adore You", artist: "Harry Styles", bpm: 108, genre: "Pop", durationMinutes: 3.5, energyScore: 7 },
  { title: "Golden", artist: "Harry Styles", bpm: 140, genre: "Pop", durationMinutes: 3.5, energyScore: 7 },
  { title: "Dynamite", artist: "BTS", bpm: 115, genre: "Pop", durationMinutes: 3.2, energyScore: 9 },
  { title: "Butter", artist: "BTS", bpm: 110, genre: "Pop", durationMinutes: 2.7, energyScore: 8 },
  { title: "Boy With Luv", artist: "BTS", bpm: 130, genre: "Pop", durationMinutes: 3.5, energyScore: 8 },
  { title: "drivers license", artist: "Olivia Rodrigo", bpm: 72, genre: "Pop", durationMinutes: 4.1, energyScore: 3 },
  { title: "good 4 u", artist: "Olivia Rodrigo", bpm: 165, genre: "Pop Rock", durationMinutes: 2.9, energyScore: 9 },
  { title: "deja vu", artist: "Olivia Rodrigo", bpm: 126, genre: "Pop", durationMinutes: 3.4, energyScore: 6 },
  { title: "brutal", artist: "Olivia Rodrigo", bpm: 130, genre: "Pop Rock", durationMinutes: 2.4, energyScore: 9 },
  { title: "Flowers", artist: "Miley Cyrus", bpm: 118, genre: "Pop", durationMinutes: 3.3, energyScore: 8 },
  { title: "Wrecking Ball", artist: "Miley Cyrus", bpm: 72, genre: "Pop", durationMinutes: 3.7, energyScore: 5 },
  { title: "Party in the U.S.A.", artist: "Miley Cyrus", bpm: 96, genre: "Pop", durationMinutes: 3.3, energyScore: 8 },
  { title: "The Climb", artist: "Miley Cyrus", bpm: 76, genre: "Pop", durationMinutes: 3.6, energyScore: 5 },
  { title: "Shake It Off", artist: "Taylor Swift", bpm: 160, genre: "Pop", durationMinutes: 3.6, energyScore: 9 },
  { title: "Anti-Hero", artist: "Taylor Swift", bpm: 97, genre: "Pop", durationMinutes: 3.4, energyScore: 6 },
  { title: "Cruel Summer", artist: "Taylor Swift", bpm: 170, genre: "Pop", durationMinutes: 2.9, energyScore: 9 },
  { title: "Blank Space", artist: "Taylor Swift", bpm: 96, genre: "Pop", durationMinutes: 3.9, energyScore: 7 },
  { title: "Bad Blood", artist: "Taylor Swift", bpm: 171, genre: "Pop", durationMinutes: 3.5, energyScore: 9 },
  { title: "Style", artist: "Taylor Swift", bpm: 95, genre: "Pop", durationMinutes: 3.9, energyScore: 7 },
  { title: "Wildest Dreams", artist: "Taylor Swift", bpm: 141, genre: "Pop", durationMinutes: 3.4, energyScore: 7 },
  { title: "22", artist: "Taylor Swift", bpm: 104, genre: "Pop", durationMinutes: 3.5, energyScore: 8 },
  { title: "We Are Never Ever Getting Back Together", artist: "Taylor Swift", bpm: 160, genre: "Pop", durationMinutes: 3.2, energyScore: 8 },
  { title: "Sparks Fly", artist: "Taylor Swift", bpm: 174, genre: "Country Pop", durationMinutes: 4.1, energyScore: 8 },
  { title: "Fearless", artist: "Taylor Swift", bpm: 122, genre: "Country Pop", durationMinutes: 4.0, energyScore: 7 },
  { title: "Roar", artist: "Katy Perry", bpm: 90, genre: "Pop", durationMinutes: 3.7, energyScore: 7 },
  { title: "Firework", artist: "Katy Perry", bpm: 124, genre: "Pop", durationMinutes: 3.8, energyScore: 8 },
  { title: "Dark Horse", artist: "Katy Perry", bpm: 132, genre: "Pop", durationMinutes: 3.8, energyScore: 8 },
  { title: "Teenage Dream", artist: "Katy Perry", bpm: 120, genre: "Pop", durationMinutes: 3.8, energyScore: 8 },
  { title: "California Gurls", artist: "Katy Perry", bpm: 120, genre: "Pop", durationMinutes: 3.6, energyScore: 8 },
  { title: "I Kissed a Girl", artist: "Katy Perry", bpm: 132, genre: "Pop", durationMinutes: 3.0, energyScore: 8 },
  { title: "Hot N Cold", artist: "Katy Perry", bpm: 126, genre: "Pop", durationMinutes: 3.7, energyScore: 9 },
  { title: "Last Friday Night (T.G.I.F.)", artist: "Katy Perry", bpm: 140, genre: "Pop", durationMinutes: 3.5, energyScore: 9 },
  { title: "Uptown Funk", artist: "Mark Ronson ft. Bruno Mars", bpm: 115, genre: "Funk", durationMinutes: 4.5, energyScore: 9 },
  { title: "Treasure", artist: "Bruno Mars", bpm: 108, genre: "Funk", durationMinutes: 2.8, energyScore: 8 },
  { title: "Grenade", artist: "Bruno Mars", bpm: 111, genre: "Pop", durationMinutes: 3.7, energyScore: 6 },
  { title: "Just the Way You Are", artist: "Bruno Mars", bpm: 109, genre: "Pop", durationMinutes: 3.8, energyScore: 5 },
  { title: "Locked Out of Heaven", artist: "Bruno Mars", bpm: 144, genre: "Pop Rock", durationMinutes: 3.8, energyScore: 9 },
  { title: "The Lazy Song", artist: "Bruno Mars", bpm: 131, genre: "Pop", durationMinutes: 3.1, energyScore: 6 },
  { title: "That's What I Like", artist: "Bruno Mars", bpm: 116, genre: "R&B", durationMinutes: 3.3, energyScore: 8 },
  { title: "24K Magic", artist: "Bruno Mars", bpm: 106, genre: "Funk", durationMinutes: 3.5, energyScore: 9 },
  { title: "Levitating", artist: "Dua Lipa", bpm: 103, genre: "Pop", durationMinutes: 3.5, energyScore: 8 },
  { title: "Happier", artist: "Marshmello & Bastille", bpm: 100, genre: "Electronic", durationMinutes: 3.5, energyScore: 7 },
  { title: "Closer", artist: "The Chainsmokers", bpm: 95, genre: "Electronic", durationMinutes: 4.1, energyScore: 7 },
  { title: "Don't Let Me Down", artist: "The Chainsmokers", bpm: 160, genre: "Electronic", durationMinutes: 3.5, energyScore: 8 },
  { title: "Something Just Like This", artist: "The Chainsmokers & Coldplay", bpm: 103, genre: "Electronic", durationMinutes: 4.1, energyScore: 7 },
  { title: "Havana", artist: "Camila Cabello", bpm: 105, genre: "Pop", durationMinutes: 3.6, energyScore: 7 },
  { title: "Senorita", artist: "Shawn Mendes & Camila Cabello", bpm: 117, genre: "Pop", durationMinutes: 3.9, energyScore: 7 },
  { title: "Stitches", artist: "Shawn Mendes", bpm: 148, genre: "Pop", durationMinutes: 3.3, energyScore: 7 },
  { title: "Treat You Better", artist: "Shawn Mendes", bpm: 89, genre: "Pop", durationMinutes: 3.3, energyScore: 7 },
  { title: "In My Blood", artist: "Shawn Mendes", bpm: 162, genre: "Pop", durationMinutes: 3.5, energyScore: 7 },
  { title: "What Makes You Beautiful", artist: "One Direction", bpm: 120, genre: "Pop", durationMinutes: 3.2, energyScore: 8 },
  { title: "Story of My Life", artist: "One Direction", bpm: 122, genre: "Pop", durationMinutes: 4.2, energyScore: 6 },
  { title: "Best Song Ever", artist: "One Direction", bpm: 154, genre: "Pop", durationMinutes: 3.2, energyScore: 9 },
  { title: "Perfect", artist: "One Direction", bpm: 115, genre: "Pop", durationMinutes: 3.5, energyScore: 6 },
  { title: "Heat Waves", artist: "Glass Animals", bpm: 81, genre: "Indie", durationMinutes: 3.9, energyScore: 5 },
  { title: "Stressed Out", artist: "Twenty One Pilots", bpm: 169, genre: "Indie Pop", durationMinutes: 3.4, energyScore: 8 },
  { title: "Ride", artist: "Twenty One Pilots", bpm: 144, genre: "Indie Pop", durationMinutes: 3.6, energyScore: 8 },
  { title: "Heathens", artist: "Twenty One Pilots", bpm: 90, genre: "Indie Pop", durationMinutes: 3.0, energyScore: 7 },
  { title: "Tear in My Heart", artist: "Twenty One Pilots", bpm: 168, genre: "Indie Pop", durationMinutes: 2.9, energyScore: 9 },
  { title: "Jumpsuit", artist: "Twenty One Pilots", bpm: 140, genre: "Indie Pop", durationMinutes: 3.5, energyScore: 8 },
  { title: "Somebody That I Used to Know", artist: "Gotye", bpm: 129, genre: "Indie", durationMinutes: 4.1, energyScore: 6 },
  { title: "Feel Good Inc.", artist: "Gorillaz", bpm: 139, genre: "Indie", durationMinutes: 3.8, energyScore: 7 },
  { title: "INDUSTRY BABY", artist: "Lil Nas X", bpm: 149, genre: "Pop", durationMinutes: 3.3, energyScore: 9 },
  // Current Hits
  { title: "Flowers", artist: "Miley Cyrus", bpm: 118, genre: "Pop", durationMinutes: 3.3, energyScore: 8 },
  { title: "Unholy", artist: "Sam Smith & Kim Petras", bpm: 131, genre: "Pop", durationMinutes: 2.7, energyScore: 8 },
  { title: "Stay", artist: "The Kid LAROI & Justin Bieber", bpm: 170, genre: "Pop", durationMinutes: 2.4, energyScore: 9 },
  { title: "Peaches", artist: "Justin Bieber", bpm: 90, genre: "Pop", durationMinutes: 3.2, energyScore: 6 },
  { title: "Love Yourself", artist: "Justin Bieber", bpm: 110, genre: "Pop", durationMinutes: 3.5, energyScore: 5 },
  { title: "Sorry", artist: "Justin Bieber", bpm: 100, genre: "Pop", durationMinutes: 3.3, energyScore: 7 },
  { title: "What Do You Mean?", artist: "Justin Bieber", bpm: 125, genre: "Pop", durationMinutes: 3.3, energyScore: 7 },
  { title: "Baby", artist: "Justin Bieber", bpm: 130, genre: "Pop", durationMinutes: 3.6, energyScore: 7 },
  { title: "Intentions", artist: "Justin Bieber", bpm: 109, genre: "Pop", durationMinutes: 4.0, energyScore: 7 },
  { title: "Ghost", artist: "Justin Bieber", bpm: 130, genre: "Pop", durationMinutes: 2.7, energyScore: 6 },
  { title: "Espresso", artist: "Sabrina Carpenter", bpm: 104, genre: "Pop", durationMinutes: 2.9, energyScore: 8 },
  { title: "Please Please Please", artist: "Sabrina Carpenter", bpm: 128, genre: "Pop", durationMinutes: 3.1, energyScore: 7 },
  { title: "Feather", artist: "Sabrina Carpenter", bpm: 108, genre: "Pop", durationMinutes: 3.0, energyScore: 7 },
  { title: "Paint the Town Red", artist: "Doja Cat", bpm: 107, genre: "Hip Hop", durationMinutes: 4.4, energyScore: 8 },
  { title: "Say So", artist: "Doja Cat", bpm: 111, genre: "Pop", durationMinutes: 3.4, energyScore: 7 },
  { title: "Kiss Me More", artist: "Doja Cat", bpm: 99, genre: "R&B", durationMinutes: 3.3, energyScore: 7 },
  { title: "Woman", artist: "Doja Cat", bpm: 105, genre: "Pop", durationMinutes: 3.4, energyScore: 8 },
  { title: "Anti-Hero", artist: "Taylor Swift", bpm: 97, genre: "Pop", durationMinutes: 3.4, energyScore: 6 },
  { title: "Midnight Rain", artist: "Taylor Swift", bpm: 119, genre: "Pop", durationMinutes: 2.9, energyScore: 5 },
  { title: "Lavender Haze", artist: "Taylor Swift", bpm: 119, genre: "Pop", durationMinutes: 3.2, energyScore: 7 },
  { title: "Snow on the Beach", artist: "Taylor Swift ft. Lana Del Rey", bpm: 120, genre: "Pop", durationMinutes: 4.4, energyScore: 5 },
  { title: "Bejeweled", artist: "Taylor Swift", bpm: 128, genre: "Pop", durationMinutes: 3.5, energyScore: 8 },
  { title: "Karma", artist: "Taylor Swift", bpm: 134, genre: "Pop", durationMinutes: 3.6, energyScore: 8 },
  { title: "Maroon", artist: "Taylor Swift", bpm: 87, genre: "Pop", durationMinutes: 3.5, energyScore: 5 },
  { title: "Summerboy", artist: "Lady Gaga", bpm: 119, genre: "Pop", durationMinutes: 4.0, energyScore: 8 },
  { title: "Paparazzi", artist: "Lady Gaga", bpm: 131, genre: "Pop", durationMinutes: 3.5, energyScore: 8 },
  { title: "Telephone", artist: "Lady Gaga", bpm: 122, genre: "Pop", durationMinutes: 3.7, energyScore: 9 },
  { title: "Alejandro", artist: "Lady Gaga", bpm: 83, genre: "Pop", durationMinutes: 4.3, energyScore: 7 },
  { title: "Million Reasons", artist: "Lady Gaga", bpm: 62, genre: "Pop", durationMinutes: 3.4, energyScore: 3 },
  { title: "Hold My Hand", artist: "Lady Gaga", bpm: 76, genre: "Pop", durationMinutes: 4.1, energyScore: 5 },
  // Additional Crowd Favorites
  { title: "Don't You (Forget About Me)", artist: "Simple Minds", bpm: 120, genre: "Rock", durationMinutes: 4.2, energyScore: 7 },
  { title: "99 Red Balloons", artist: "Nena", bpm: 134, genre: "Pop", durationMinutes: 3.8, energyScore: 7 },
  { title: "Take Me Home Tonight", artist: "Eddie Money", bpm: 120, genre: "Rock", durationMinutes: 4.1, energyScore: 8 },
  { title: "I Love Rock 'N Roll", artist: "Joan Jett", bpm: 138, genre: "Rock", durationMinutes: 2.8, energyScore: 9 },
  { title: "Bad Reputation", artist: "Joan Jett", bpm: 144, genre: "Rock", durationMinutes: 2.7, energyScore: 9 },
  { title: "Mickey", artist: "Toni Basil", bpm: 175, genre: "Pop", durationMinutes: 3.3, energyScore: 9 },
  { title: "Livin' la Vida Loca", artist: "Ricky Martin", bpm: 178, genre: "Pop", durationMinutes: 4.0, energyScore: 9 },
  { title: "She Bangs", artist: "Ricky Martin", bpm: 140, genre: "Pop", durationMinutes: 4.0, energyScore: 8 },
  { title: "Hips Don't Lie", artist: "Shakira", bpm: 100, genre: "Pop", durationMinutes: 3.6, energyScore: 8 },
  { title: "Whenever, Wherever", artist: "Shakira", bpm: 100, genre: "Pop", durationMinutes: 3.4, energyScore: 8 },
  { title: "Waka Waka (This Time for Africa)", artist: "Shakira", bpm: 131, genre: "Pop", durationMinutes: 3.5, energyScore: 9 },
  { title: "La Bamba", artist: "Los Lobos", bpm: 160, genre: "Rock", durationMinutes: 2.1, energyScore: 9 },
  { title: "Bamboleo", artist: "Gipsy Kings", bpm: 148, genre: "Flamenco", durationMinutes: 3.6, energyScore: 9 },
  { title: "My Sharona", artist: "The Knack", bpm: 148, genre: "Rock", durationMinutes: 4.9, energyScore: 9 },
  { title: "I Love a Rainy Night", artist: "Eddie Rabbitt", bpm: 150, genre: "Country", durationMinutes: 3.2, energyScore: 8 },
  { title: "Jessie's Girl", artist: "Rick Springfield", bpm: 140, genre: "Rock", durationMinutes: 3.3, energyScore: 9 },
  { title: "867-5309/Jenny", artist: "Tommy Tutone", bpm: 148, genre: "Rock", durationMinutes: 2.9, energyScore: 9 },
  { title: "Come On Eileen", artist: "Dexys Midnight Runners", bpm: 115, genre: "Pop", durationMinutes: 4.3, energyScore: 9 },
  { title: "Eternal Flame", artist: "The Bangles", bpm: 68, genre: "Pop", durationMinutes: 4.0, energyScore: 4 },
  { title: "Walk Like an Egyptian", artist: "The Bangles", bpm: 135, genre: "Pop", durationMinutes: 3.3, energyScore: 8 },
  { title: "Manic Monday", artist: "The Bangles", bpm: 140, genre: "Pop", durationMinutes: 3.1, energyScore: 7 },
  { title: "Kiss You All Over", artist: "Exile", bpm: 102, genre: "Pop", durationMinutes: 4.2, energyScore: 6 },
  { title: "Obsession", artist: "Animotion", bpm: 125, genre: "Synthpop", durationMinutes: 3.6, energyScore: 8 },
  { title: "Bette Davis Eyes", artist: "Kim Carnes", bpm: 118, genre: "Pop", durationMinutes: 3.7, energyScore: 6 },
  { title: "I Ran (So Far Away)", artist: "A Flock of Seagulls", bpm: 130, genre: "Synthpop", durationMinutes: 3.6, energyScore: 7 },
  { title: "99 Luftballons", artist: "Nena", bpm: 132, genre: "Pop", durationMinutes: 3.8, energyScore: 7 },
  { title: "Maniac", artist: "Michael Sembello", bpm: 130, genre: "Pop", durationMinutes: 3.9, energyScore: 8 },
  { title: "What a Feeling", artist: "Irene Cara", bpm: 120, genre: "Pop", durationMinutes: 3.9, energyScore: 8 },
  { title: "Gloria", artist: "Laura Branigan", bpm: 120, genre: "Pop", durationMinutes: 4.4, energyScore: 8 },
  { title: "Footloose", artist: "Kenny Loggins", bpm: 172, genre: "Pop", durationMinutes: 3.7, energyScore: 9 },
  { title: "Danger Zone", artist: "Kenny Loggins", bpm: 150, genre: "Pop", durationMinutes: 3.5, energyScore: 9 },
  { title: "The Power of Love", artist: "Huey Lewis and the News", bpm: 112, genre: "Rock", durationMinutes: 3.6, energyScore: 7 },
  { title: "I Want a New Drug", artist: "Huey Lewis and the News", bpm: 116, genre: "Rock", durationMinutes: 3.8, energyScore: 7 },
  { title: "Hip to Be Square", artist: "Huey Lewis and the News", bpm: 140, genre: "Rock", durationMinutes: 3.4, energyScore: 8 },
  { title: "Oh Sherrie", artist: "Steve Perry", bpm: 86, genre: "Pop", durationMinutes: 3.9, energyScore: 6 },
  { title: "Don't Stop Me Now", artist: "Queen", bpm: 156, genre: "Rock", durationMinutes: 3.6, energyScore: 10 },
  { title: "Bohemian Rhapsody", artist: "Queen", bpm: 72, genre: "Rock", durationMinutes: 5.9, energyScore: 7 },
  // 90s Hits
  { title: "Waterfalls", artist: "TLC", bpm: 96, genre: "R&B", durationMinutes: 4.4, energyScore: 5 },
  { title: "Losing My Religion", artist: "R.E.M.", bpm: 124, genre: "Rock", durationMinutes: 4.4, energyScore: 5 },
  { title: "Everybody Hurts", artist: "R.E.M.", bpm: 72, genre: "Rock", durationMinutes: 5.3, energyScore: 3 },
  { title: "Man on the Moon", artist: "R.E.M.", bpm: 112, genre: "Rock", durationMinutes: 5.2, energyScore: 5 },
  { title: "I'm Gonna Be (500 Miles)", artist: "The Proclaimers", bpm: 133, genre: "Folk Rock", durationMinutes: 3.3, energyScore: 9 },
  { title: "When I'm Cleaning Windows", artist: "George Formby", bpm: 130, genre: "Classic", durationMinutes: 2.9, energyScore: 7 },
  { title: "What's Up", artist: "4 Non Blondes", bpm: 122, genre: "Rock", durationMinutes: 5.2, energyScore: 6 },
  { title: "More Than Words", artist: "Extreme", bpm: 72, genre: "Rock", durationMinutes: 5.3, energyScore: 3 },
  { title: "November Rain", artist: "Guns N' Roses", bpm: 76, genre: "Rock", durationMinutes: 8.9, energyScore: 5 },
  { title: "Paradise City", artist: "Guns N' Roses", bpm: 99, genre: "Rock", durationMinutes: 6.5, energyScore: 8 },
  { title: "Welcome to the Jungle", artist: "Guns N' Roses", bpm: 105, genre: "Rock", durationMinutes: 4.5, energyScore: 9 },
  { title: "Sweet Child O' Mine", artist: "Guns N' Roses", bpm: 124, genre: "Rock", durationMinutes: 5.6, energyScore: 8 },
  { title: "Patience", artist: "Guns N' Roses", bpm: 112, genre: "Rock", durationMinutes: 5.5, energyScore: 5 },
  { title: "Mr. Jones", artist: "Counting Crows", bpm: 133, genre: "Rock", durationMinutes: 4.5, energyScore: 7 },
  { title: "Round Here", artist: "Counting Crows", bpm: 110, genre: "Rock", durationMinutes: 5.5, energyScore: 5 },
  { title: "Ordinary World", artist: "Duran Duran", bpm: 88, genre: "Pop", durationMinutes: 5.4, energyScore: 4 },
  { title: "Linger", artist: "The Cranberries", bpm: 80, genre: "Rock", durationMinutes: 4.7, energyScore: 3 },
  { title: "Zombie", artist: "The Cranberries", bpm: 84, genre: "Rock", durationMinutes: 5.1, energyScore: 6 },
  { title: "Dreams", artist: "The Cranberries", bpm: 132, genre: "Rock", durationMinutes: 4.6, energyScore: 6 },
  { title: "Push", artist: "Matchbox Twenty", bpm: 106, genre: "Rock", durationMinutes: 4.6, energyScore: 6 },
  { title: "3 A.M.", artist: "Matchbox Twenty", bpm: 130, genre: "Rock", durationMinutes: 4.3, energyScore: 6 },
  { title: "Unwell", artist: "Matchbox Twenty", bpm: 82, genre: "Rock", durationMinutes: 3.8, energyScore: 5 },
  { title: "Smooth", artist: "Santana ft. Rob Thomas", bpm: 113, genre: "Rock", durationMinutes: 4.6, energyScore: 7 },
  { title: "Maria Maria", artist: "Santana", bpm: 116, genre: "Rock", durationMinutes: 4.4, energyScore: 7 },
  { title: "Scar Tissue", artist: "Red Hot Chili Peppers", bpm: 92, genre: "Rock", durationMinutes: 3.5, energyScore: 5 },
  { title: "Under the Bridge", artist: "Red Hot Chili Peppers", bpm: 77, genre: "Rock", durationMinutes: 4.5, energyScore: 4 },
  { title: "Give It Away", artist: "Red Hot Chili Peppers", bpm: 94, genre: "Rock", durationMinutes: 4.4, energyScore: 8 },
  { title: "Californication", artist: "Red Hot Chili Peppers", bpm: 96, genre: "Rock", durationMinutes: 5.5, energyScore: 5 },
  { title: "Soul to Squeeze", artist: "Red Hot Chili Peppers", bpm: 88, genre: "Rock", durationMinutes: 4.9, energyScore: 5 },
  { title: "Otherside", artist: "Red Hot Chili Peppers", bpm: 84, genre: "Rock", durationMinutes: 4.1, energyScore: 5 },
  { title: "Wonderwall", artist: "Oasis", bpm: 87, genre: "Rock", durationMinutes: 4.3, energyScore: 6 },
  { title: "Stand By Me", artist: "Ben E. King", bpm: 116, genre: "Soul", durationMinutes: 2.9, energyScore: 5 },
  { title: "I Got You (I Feel Good)", artist: "James Brown", bpm: 150, genre: "Funk", durationMinutes: 2.7, energyScore: 9 },
  { title: "Sex Machine", artist: "James Brown", bpm: 100, genre: "Funk", durationMinutes: 5.3, energyScore: 9 },
  { title: "Get Up Offa That Thing", artist: "James Brown", bpm: 120, genre: "Funk", durationMinutes: 3.3, energyScore: 9 },
  // 2000s
  { title: "Toxic", artist: "Britney Spears", bpm: 143, genre: "Pop", durationMinutes: 3.3, energyScore: 9 },
  { title: "Sk8er Boi", artist: "Avril Lavigne", bpm: 173, genre: "Pop Rock", durationMinutes: 3.4, energyScore: 9 },
  { title: "Complicated", artist: "Avril Lavigne", bpm: 111, genre: "Pop Rock", durationMinutes: 4.1, energyScore: 7 },
  { title: "I'm With You", artist: "Avril Lavigne", bpm: 80, genre: "Pop Rock", durationMinutes: 3.7, energyScore: 5 },
  { title: "Girlfriend", artist: "Avril Lavigne", bpm: 172, genre: "Pop Rock", durationMinutes: 3.3, energyScore: 8 },
  { title: "Since U Been Gone", artist: "Kelly Clarkson", bpm: 168, genre: "Pop Rock", durationMinutes: 3.1, energyScore: 9 },
  { title: "Because of You", artist: "Kelly Clarkson", bpm: 63, genre: "Pop", durationMinutes: 3.8, energyScore: 4 },
  { title: "Breakaway", artist: "Kelly Clarkson", bpm: 100, genre: "Pop", durationMinutes: 3.9, energyScore: 6 },
  { title: "Behind These Hazel Eyes", artist: "Kelly Clarkson", bpm: 145, genre: "Pop Rock", durationMinutes: 3.1, energyScore: 8 },
  { title: "Stronger (What Doesn't Kill You)", artist: "Kelly Clarkson", bpm: 136, genre: "Pop", durationMinutes: 3.4, energyScore: 8 },
  { title: "Mr. Brightside", artist: "The Killers", bpm: 148, genre: "Rock", durationMinutes: 3.7, energyScore: 9 },
  { title: "Somebody Told Me", artist: "The Killers", bpm: 136, genre: "Rock", durationMinutes: 3.3, energyScore: 9 },
  { title: "Are You Gonna Be My Girl", artist: "Jet", bpm: 200, genre: "Rock", durationMinutes: 3.6, energyScore: 9 },
  { title: "Look What You Made Me Do", artist: "Taylor Swift", bpm: 128, genre: "Pop", durationMinutes: 3.5, energyScore: 8 },
  { title: "Teardrops on My Guitar", artist: "Taylor Swift", bpm: 118, genre: "Country Pop", durationMinutes: 3.5, energyScore: 4 },
  { title: "Our Song", artist: "Taylor Swift", bpm: 139, genre: "Country Pop", durationMinutes: 3.4, energyScore: 7 },
  { title: "Apologize", artist: "Timbaland ft. OneRepublic", bpm: 88, genre: "Pop", durationMinutes: 3.3, energyScore: 5 },
  { title: "Counting Stars", artist: "OneRepublic", bpm: 122, genre: "Pop", durationMinutes: 4.3, energyScore: 7 },
  { title: "Secrets", artist: "OneRepublic", bpm: 116, genre: "Pop", durationMinutes: 4.0, energyScore: 6 },
  { title: "Stop and Stare", artist: "OneRepublic", bpm: 128, genre: "Pop", durationMinutes: 4.1, energyScore: 6 },
  { title: "Poker Face", artist: "Lady Gaga", bpm: 120, genre: "Pop", durationMinutes: 3.6, energyScore: 8 },
  { title: "Let Me Love You", artist: "Mario", bpm: 64, genre: "R&B", durationMinutes: 4.2, energyScore: 4 },
  { title: "Crazy in Love", artist: "Beyoncé", bpm: 99, genre: "R&B", durationMinutes: 3.9, energyScore: 9 },
  { title: "Gold Digger", artist: "Kanye West", bpm: 112, genre: "Hip Hop", durationMinutes: 3.3, energyScore: 8 },
  { title: "Yeah!", artist: "Usher", bpm: 100, genre: "R&B", durationMinutes: 4.5, energyScore: 9 },
  { title: "Confessions Part II", artist: "Usher", bpm: 98, genre: "R&B", durationMinutes: 4.4, energyScore: 6 },
  { title: "U Remind Me", artist: "Usher", bpm: 94, genre: "R&B", durationMinutes: 4.2, energyScore: 6 },
  { title: "Burn", artist: "Usher", bpm: 75, genre: "R&B", durationMinutes: 4.9, energyScore: 4 },
  { title: "Nice & Slow", artist: "Usher", bpm: 72, genre: "R&B", durationMinutes: 5.4, energyScore: 3 },
  { title: "U Got It Bad", artist: "Usher", bpm: 72, genre: "R&B", durationMinutes: 4.4, energyScore: 3 },
  { title: "In Da Club", artist: "50 Cent", bpm: 89, genre: "Hip Hop", durationMinutes: 3.8, energyScore: 9 },
  { title: "21 Questions", artist: "50 Cent", bpm: 85, genre: "Hip Hop", durationMinutes: 4.2, energyScore: 5 },
  { title: "Just a Friend 2002", artist: "Mario", bpm: 86, genre: "R&B", durationMinutes: 4.2, energyScore: 7 },
  { title: "Crazy", artist: "Gnarls Barkley", bpm: 112, genre: "Soul", durationMinutes: 3.0, energyScore: 7 },
  { title: "Mercy", artist: "Duffy", bpm: 105, genre: "Soul", durationMinutes: 3.7, energyScore: 7 },
  { title: "Rehab", artist: "Amy Winehouse", bpm: 90, genre: "Soul", durationMinutes: 3.3, energyScore: 7 },
  { title: "Back to Black", artist: "Amy Winehouse", bpm: 119, genre: "Soul", durationMinutes: 4.0, energyScore: 5 },
  { title: "Valerie", artist: "Amy Winehouse", bpm: 91, genre: "Soul", durationMinutes: 3.5, energyScore: 7 },
  // Indie & Alternative
  { title: "Mr. Brightside", artist: "The Killers", bpm: 148, genre: "Rock", durationMinutes: 3.7, energyScore: 9 },
  { title: "Take Me Out", artist: "Franz Ferdinand", bpm: 104, genre: "Indie Rock", durationMinutes: 3.6, energyScore: 9 },
  { title: "Do You Want To", artist: "Franz Ferdinand", bpm: 120, genre: "Indie Rock", durationMinutes: 3.5, energyScore: 8 },
  { title: "Reptilia", artist: "The Strokes", bpm: 160, genre: "Indie Rock", durationMinutes: 3.7, energyScore: 9 },
  { title: "Last Nite", artist: "The Strokes", bpm: 157, genre: "Indie Rock", durationMinutes: 3.4, energyScore: 9 },
  { title: "Someday", artist: "The Strokes", bpm: 168, genre: "Indie Rock", durationMinutes: 3.0, energyScore: 8 },
  { title: "Maps", artist: "Yeah Yeah Yeahs", bpm: 106, genre: "Indie Rock", durationMinutes: 3.7, energyScore: 5 },
  { title: "Heads Will Roll", artist: "Yeah Yeah Yeahs", bpm: 128, genre: "Indie Rock", durationMinutes: 3.7, energyScore: 8 },
  { title: "Seven Nation Army", artist: "The White Stripes", bpm: 124, genre: "Rock", durationMinutes: 3.5, energyScore: 8 },
  { title: "Icky Thump", artist: "The White Stripes", bpm: 136, genre: "Rock", durationMinutes: 4.1, energyScore: 8 },
  { title: "Fell in Love with a Girl", artist: "The White Stripes", bpm: 158, genre: "Rock", durationMinutes: 1.9, energyScore: 9 },
  { title: "Float On", artist: "Modest Mouse", bpm: 168, genre: "Indie Rock", durationMinutes: 3.3, energyScore: 7 },
  { title: "Dashboard", artist: "Modest Mouse", bpm: 160, genre: "Indie Rock", durationMinutes: 4.2, energyScore: 7 },
  { title: "Such Great Heights", artist: "The Postal Service", bpm: 148, genre: "Electronic", durationMinutes: 4.4, energyScore: 7 },
  { title: "The District Sleeps Alone Tonight", artist: "The Postal Service", bpm: 116, genre: "Electronic", durationMinutes: 4.6, energyScore: 5 },
  { title: "Riptide", artist: "Vance Joy", bpm: 162, genre: "Folk Pop", durationMinutes: 3.3, energyScore: 7 },
  { title: "Fire and the Flood", artist: "Vance Joy", bpm: 130, genre: "Folk Pop", durationMinutes: 3.8, energyScore: 6 },
  { title: "Ho Hey", artist: "The Lumineers", bpm: 156, genre: "Folk Rock", durationMinutes: 3.1, energyScore: 8 },
  { title: "Stubborn Love", artist: "The Lumineers", bpm: 150, genre: "Folk Rock", durationMinutes: 4.3, energyScore: 6 },
  { title: "Cleopatra", artist: "The Lumineers", bpm: 146, genre: "Folk Rock", durationMinutes: 3.8, energyScore: 6 },
  { title: "Home", artist: "Edward Sharpe and the Magnetic Zeros", bpm: 112, genre: "Folk Rock", durationMinutes: 5.5, energyScore: 7 },
  { title: "I and Love and You", artist: "The Avett Brothers", bpm: 78, genre: "Folk Rock", durationMinutes: 4.8, energyScore: 4 },
  { title: "Head Full of Doubt/Road Full of Promise", artist: "The Avett Brothers", bpm: 148, genre: "Folk Rock", durationMinutes: 4.3, energyScore: 7 },
  { title: "Pompeii", artist: "Bastille", bpm: 126, genre: "Indie Pop", durationMinutes: 3.3, energyScore: 8 },
  { title: "Of the Night", artist: "Bastille", bpm: 126, genre: "Indie Pop", durationMinutes: 4.1, energyScore: 8 },
  { title: "Good Grief", artist: "Bastille", bpm: 97, genre: "Indie Pop", durationMinutes: 3.5, energyScore: 7 },
  { title: "Little Talks", artist: "Of Monsters and Men", bpm: 98, genre: "Indie Folk", durationMinutes: 4.4, energyScore: 7 },
  { title: "Mountain Sound", artist: "Of Monsters and Men", bpm: 167, genre: "Indie Folk", durationMinutes: 3.7, energyScore: 8 },
  { title: "King of Anything", artist: "Sara Bareilles", bpm: 120, genre: "Pop", durationMinutes: 4.2, energyScore: 7 },
  { title: "Love Song", artist: "Sara Bareilles", bpm: 155, genre: "Pop", durationMinutes: 4.2, energyScore: 7 },
  { title: "Brave", artist: "Sara Bareilles", bpm: 160, genre: "Pop", durationMinutes: 3.7, energyScore: 8 },
  { title: "Chandelier", artist: "Sia", bpm: 130, genre: "Pop", durationMinutes: 3.6, energyScore: 8 },
  { title: "Cheap Thrills", artist: "Sia", bpm: 104, genre: "Pop", durationMinutes: 3.5, energyScore: 7 },
  { title: "Elastic Heart", artist: "Sia", bpm: 133, genre: "Pop", durationMinutes: 4.4, energyScore: 7 },
  { title: "The Greatest", artist: "Sia", bpm: 128, genre: "Pop", durationMinutes: 3.9, energyScore: 7 },
  { title: "Latch", artist: "Disclosure ft. Sam Smith", bpm: 122, genre: "Electronic", durationMinutes: 4.2, energyScore: 7 },
  { title: "Stay With Me", artist: "Sam Smith", bpm: 87, genre: "Soul", durationMinutes: 2.8, energyScore: 5 },
  { title: "I'm Not the Only One", artist: "Sam Smith", bpm: 58, genre: "Soul", durationMinutes: 3.6, energyScore: 4 },
  { title: "Writing's on the Wall", artist: "Sam Smith", bpm: 76, genre: "Soul", durationMinutes: 4.4, energyScore: 5 },
  { title: "Promises", artist: "Sam Smith", bpm: 99, genre: "Soul", durationMinutes: 3.6, energyScore: 6 },
];

export async function seedSongs(): Promise<void> {
  const rows = await db.select().from(songs).limit(1);
  if (rows.length > 0) return;

  console.log("[Seed] Inserting seed songs...");
  for (const song of SEED_SONGS) {
    await db.insert(songs).values(song);
  }
  console.log(`[Seed] Inserted ${SEED_SONGS.length} songs.`);
}
